CREATE DATABASE COTADOR
GO

USE COTADOR
GO

-- TIPO USUARIO
CREATE TABLE TIPOUSUARIO(
	idTipoUsuario SMALLINT PRIMARY KEY IDENTITY,
	titulo VARCHAR(60) NOT NULL
)
GO

-- USUARIO
CREATE TABLE USUARIO (
	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	nome VARCHAR(100),
	email VARCHAR(255) NOT NULL UNIQUE,
	senha VARCHAR(100) NOT NULL
)
GO
-- CLIENTE
CREATE TABLE CLIENTE (
	idCliente INT PRIMARY KEY IDENTITY,
	idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario) UNIQUE,
	telefone VARCHAR(30) NOT NULL
)
GO

-- SEGURADORA
CREATE TABLE SEGURADORA(
	idSeguradora SMALLINT PRIMARY KEY IDENTITY,
	nome VARCHAR(150) NOT NULL UNIQUE
)
GO
-- CULTURA
CREATE TABLE CULTURA (
	idCultura SMALLINT PRIMARY KEY IDENTITY,
	nome VARCHAR(60) NOT NULL UNIQUE
)
GO

-- NIVEL COBERTURA
CREATE TABLE NIVELCOBERTURA (
	idNivelCobertura TINYINT PRIMARY KEY IDENTITY,
	valor TINYINT NOT NULL
)
GO
-- UF
CREATE TABLE UF (
	idUf SMALLINT PRIMARY KEY IDENTITY,
	titulo VARCHAR(150)
)
GO

-- MUNICIPIO
CREATE TABLE MUNICIPIO (
	idMunicipio INT PRIMARY KEY IDENTITY,
	idUf SMALLINT FOREIGN KEY REFERENCES UF(idUf),
	nome VARCHAR(255)
)
GO
-- PLANTIO
CREATE TABLE PLANTIO (
	idPlantio INT PRIMARY KEY IDENTITY,
	idSeguradora SMALLINT FOREIGN KEY REFERENCES SEGURADORA(idSeguradora),
	idNivelCobertura TINYINT FOREIGN KEY REFERENCES NIVELCOBERTURA(idNivelCobertura),
	idCultura SMALLINT FOREIGN KEY REFERENCES CULTURA(idCultura),
	idMunicipio INT FOREIGN KEY REFERENCES MUNICIPIO(idMunicipio)
)
GO


CREATE TABLE VERSAOSACA(
	idVersaoSaca SMALLINT PRIMARY KEY IDENTITY,
	valor VARCHAR(80) NOT NULL
)
GO


-- COTACAO
CREATE TABLE COTACAO(
	idCotacao INT PRIMARY KEY IDENTITY,
	idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	idPlantio INT FOREIGN KEY REFERENCES PLANTIO (idPlantio),
	versaoSaca SMALLINT FOREIGN KEY REFERENCES VERSAOSACA(idVersaoSaca),
	taxaBasica FLOAT NOT NULL,
	taxaReplantio FLOAT NOT NULL,
	valorSaca FLOAT NOT NULL,
	produtividadeEsperada INT NOT NULL,
	LMGAReplantio INT NOT NULL,
	periodoSaca DATE NOT NULL,
	
)
GO